<?php
// Generated by tests/make-integrity.php — do not edit by hand.
return array (
  '.htaccess' => 
  array (
    'size' => 656,
    'md5' => '521bc17139247a7633f902f6d46d3e7c',
  ),
  'README.md' => 
  array (
    'size' => 7787,
    'md5' => '425c0d8a89131c27518bfd2262268b63',
  ),
  'UPLOAD-INSTRUCTIONS.txt' => 
  array (
    'size' => 5725,
    'md5' => '8aacbadf968b6fe6cbb2f721f3bbea96',
  ),
  'assets/css/style.css' => 
  array (
    'size' => 34223,
    'md5' => '70f8a941e9b31b93368219c13a59018f',
  ),
  'assets/js/app.js' => 
  array (
    'size' => 5892,
    'md5' => '9a1de53cd80acfe6a54cba28d71bdf70',
  ),
  'htaccess.txt' => 
  array (
    'size' => 656,
    'md5' => '521bc17139247a7633f902f6d46d3e7c',
  ),
  'includes/auth.php' => 
  array (
    'size' => 4647,
    'md5' => 'acecabc29e8fd674f7cd561707bfcf7b',
  ),
  'includes/bootstrap.php' => 
  array (
    'size' => 3950,
    'md5' => 'fcb00024c18bb4628168b7b4bde876d4',
  ),
  'includes/db.php' => 
  array (
    'size' => 2855,
    'md5' => '787ee9ee57b932c787152cd9ca57e240',
  ),
  'includes/helpers.php' => 
  array (
    'size' => 9315,
    'md5' => '33e66ec8e0c8c027cfe7932f635f955d',
  ),
  'includes/i18n.php' => 
  array (
    'size' => 3814,
    'md5' => '3ad50753c0784cac9c506c36182d8fef',
  ),
  'includes/layout.php' => 
  array (
    'size' => 10925,
    'md5' => '202a42a0c943a9ef85199c0468399e77',
  ),
  'includes/models.php' => 
  array (
    'size' => 29071,
    'md5' => 'be5b3c42e94907049fac2904cdc0590d',
  ),
  'index.php' => 
  array (
    'size' => 1968,
    'md5' => 'a6c4a1c9596ff973fbd6fdfd4049849d',
  ),
  'install.php' => 
  array (
    'size' => 16654,
    'md5' => '459822cadaf0aea876440535bc068611',
  ),
  'lang/ar.php' => 
  array (
    'size' => 26319,
    'md5' => '30761f5f611e0af0c682999a2fb2b62f',
  ),
  'lang/de.php' => 
  array (
    'size' => 23549,
    'md5' => '5921932fa271aceeeac772539761ec39',
  ),
  'lang/doc-ar.php' => 
  array (
    'size' => 13496,
    'md5' => '0d11e4fe9e347ae79017edcc6f56fd54',
  ),
  'lang/doc-de.php' => 
  array (
    'size' => 11824,
    'md5' => 'ea60f679bb9c582fe859fab3bb210951',
  ),
  'lang/doc-en.php' => 
  array (
    'size' => 10850,
    'md5' => 'b3c69c7aefdce9c4496b54bd8be7b55f',
  ),
  'lang/en.php' => 
  array (
    'size' => 21934,
    'md5' => 'd74aa65020e8f7ba25c7ac2c245f5eaa',
  ),
  'pages/404.php' => 
  array (
    'size' => 592,
    'md5' => 'a03727003f57b5209035c81d6a3a1b9b',
  ),
  'pages/admin/audit.php' => 
  array (
    'size' => 2371,
    'md5' => 'e2c66b2bd86d3b4555789d032576bd5e',
  ),
  'pages/admin/categories.php' => 
  array (
    'size' => 3667,
    'md5' => '162edf49c2bb7004aca8b1fbb08bcca8',
  ),
  'pages/admin/kb.php' => 
  array (
    'size' => 6770,
    'md5' => 'd6b69dbfa38cf852135c2b9e9303d286',
  ),
  'pages/admin/reports.php' => 
  array (
    'size' => 5755,
    'md5' => 'a01852c827ee70675ae4124440cc7f37',
  ),
  'pages/admin/settings.php' => 
  array (
    'size' => 3336,
    'md5' => 'fc8a0a6e5fd7f729c09762978152a2dd',
  ),
  'pages/admin/users.php' => 
  array (
    'size' => 7717,
    'md5' => 'a114d39f59353cf4daa231e6509b33f3',
  ),
  'pages/api.php' => 
  array (
    'size' => 1672,
    'md5' => '86cded1d9ae861d704978cf5927cd17f',
  ),
  'pages/article.php' => 
  array (
    'size' => 3058,
    'md5' => '8dc41bfb259c9a4ce09c37d9bd081b54',
  ),
  'pages/dashboard.php' => 
  array (
    'size' => 6045,
    'md5' => 'f95d6500f3be2d9728b8fc0a200dc7d1',
  ),
  'pages/doc.php' => 
  array (
    'size' => 4425,
    'md5' => '62682432fe034041b62345bcd3ef856d',
  ),
  'pages/download.php' => 
  array (
    'size' => 840,
    'md5' => '51452b580a408f645b4eb5798d3bdbdf',
  ),
  'pages/kb.php' => 
  array (
    'size' => 3013,
    'md5' => 'b87708cdca2df2ffdc0e9d89e2c46398',
  ),
  'pages/login.php' => 
  array (
    'size' => 2890,
    'md5' => '44056a12bc2fb57c8e1a545d6783661f',
  ),
  'pages/logout.php' => 
  array (
    'size' => 91,
    'md5' => 'fb234c1c641adadb4abf9fb61cf0a419',
  ),
  'pages/notifications.php' => 
  array (
    'size' => 1336,
    'md5' => 'acbb40ea2e78b4e1f28a0412b8c03792',
  ),
  'pages/profile.php' => 
  array (
    'size' => 3208,
    'md5' => 'aebc63a672f1fceed392a91e3cd0c64c',
  ),
  'pages/ticket_new.php' => 
  array (
    'size' => 3759,
    'md5' => 'f62a2cea6eaf6b8ec8c9147ea55f565b',
  ),
  'pages/ticket_view.php' => 
  array (
    'size' => 11445,
    'md5' => '9b4b2d4bd4145fb0b13196271257c084',
  ),
  'pages/tickets.php' => 
  array (
    'size' => 4094,
    'md5' => 'f1ec76a5dbda438cef338ab76a2e29ab',
  ),
  'seed.php' => 
  array (
    'size' => 16124,
    'md5' => 'd608553650c02872ce80301d12713297',
  ),
  'sql/schema.mysql.sql' => 
  array (
    'size' => 6061,
    'md5' => 'f1313bf6c00bf2431c5dd709f44b85bb',
  ),
  'sql/schema.sqlite.sql' => 
  array (
    'size' => 5331,
    'md5' => '0f8cd9ecc902e87e6046566f5cca7076',
  ),
);
