<?php
// Generated by tests/make-integrity.php — do not edit by hand.
return array (
  '.htaccess' => 
  array (
    'size' => 836,
    'md5' => 'ba9333934205c971e40778d9d04c46e7',
  ),
  'README.md' => 
  array (
    'size' => 8356,
    'md5' => '5e282abc190f522ba59082145f97189f',
  ),
  'UPLOAD-INSTRUCTIONS.txt' => 
  array (
    'size' => 7117,
    'md5' => '253dde8e6881f859f059a1cc37991804',
  ),
  'assets/css/style.css' => 
  array (
    'size' => 34923,
    'md5' => 'dcd345baad609c946514368d19318712',
  ),
  'assets/js/app.js' => 
  array (
    'size' => 5892,
    'md5' => '9a1de53cd80acfe6a54cba28d71bdf70',
  ),
  'htaccess.txt' => 
  array (
    'size' => 836,
    'md5' => 'ba9333934205c971e40778d9d04c46e7',
  ),
  'includes/auth.php' => 
  array (
    'size' => 4647,
    'md5' => 'acecabc29e8fd674f7cd561707bfcf7b',
  ),
  'includes/bootstrap.php' => 
  array (
    'size' => 3950,
    'md5' => 'fcb00024c18bb4628168b7b4bde876d4',
  ),
  'includes/db.php' => 
  array (
    'size' => 2855,
    'md5' => '787ee9ee57b932c787152cd9ca57e240',
  ),
  'includes/helpers.php' => 
  array (
    'size' => 10423,
    'md5' => '6884b11f503ea6f147f57e43aca4e7bb',
  ),
  'includes/i18n.php' => 
  array (
    'size' => 3814,
    'md5' => '3ad50753c0784cac9c506c36182d8fef',
  ),
  'includes/layout.php' => 
  array (
    'size' => 12353,
    'md5' => 'f7e48e5f064be9901d7813e646bec735',
  ),
  'includes/models.php' => 
  array (
    'size' => 30319,
    'md5' => '59db8cd4cd19909e8025ce27b2b60f40',
  ),
  'index.php' => 
  array (
    'size' => 1968,
    'md5' => 'a6c4a1c9596ff973fbd6fdfd4049849d',
  ),
  'install.php' => 
  array (
    'size' => 16834,
    'md5' => 'a4aef6cd6972ce77dd48dbb0df5d52d4',
  ),
  'lang/ar.php' => 
  array (
    'size' => 27073,
    'md5' => 'b4be6d439b87bf068991fac9d5db14c1',
  ),
  'lang/de.php' => 
  array (
    'size' => 24206,
    'md5' => '39fafdf0f1152e62712a0c68e33ed6ee',
  ),
  'lang/doc-ar.php' => 
  array (
    'size' => 13496,
    'md5' => '0d11e4fe9e347ae79017edcc6f56fd54',
  ),
  'lang/doc-de.php' => 
  array (
    'size' => 11824,
    'md5' => 'ea60f679bb9c582fe859fab3bb210951',
  ),
  'lang/doc-en.php' => 
  array (
    'size' => 10850,
    'md5' => 'b3c69c7aefdce9c4496b54bd8be7b55f',
  ),
  'lang/en.php' => 
  array (
    'size' => 22552,
    'md5' => 'b0b3c61ab1e3d2ffcdad835a41e3fc32',
  ),
  'pages/404.php' => 
  array (
    'size' => 166,
    'md5' => '233a380893b4d829f3aaacfe906288d5',
  ),
  'pages/admin/audit.php' => 
  array (
    'size' => 2371,
    'md5' => 'e2c66b2bd86d3b4555789d032576bd5e',
  ),
  'pages/admin/categories.php' => 
  array (
    'size' => 3919,
    'md5' => '4d7028fb66cf36f6d8c14dafe34cdea1',
  ),
  'pages/admin/kb.php' => 
  array (
    'size' => 7022,
    'md5' => 'f743777fd2adef5859382efcaae73cb0',
  ),
  'pages/admin/reports.php' => 
  array (
    'size' => 5755,
    'md5' => 'a01852c827ee70675ae4124440cc7f37',
  ),
  'pages/admin/settings.php' => 
  array (
    'size' => 3336,
    'md5' => 'fc8a0a6e5fd7f729c09762978152a2dd',
  ),
  'pages/admin/users.php' => 
  array (
    'size' => 7835,
    'md5' => '1ae854fd13aae266eae1936b40a41dba',
  ),
  'pages/api.php' => 
  array (
    'size' => 1672,
    'md5' => '86cded1d9ae861d704978cf5927cd17f',
  ),
  'pages/article.php' => 
  array (
    'size' => 3070,
    'md5' => '7af8f1e463d67228f25da80689fa466e',
  ),
  'pages/dashboard.php' => 
  array (
    'size' => 6361,
    'md5' => '8319b114015122ebd68ad312baf996c0',
  ),
  'pages/doc.php' => 
  array (
    'size' => 4425,
    'md5' => '62682432fe034041b62345bcd3ef856d',
  ),
  'pages/download.php' => 
  array (
    'size' => 840,
    'md5' => '51452b580a408f645b4eb5798d3bdbdf',
  ),
  'pages/kb.php' => 
  array (
    'size' => 3013,
    'md5' => 'b87708cdca2df2ffdc0e9d89e2c46398',
  ),
  'pages/login.php' => 
  array (
    'size' => 3147,
    'md5' => '3cefdc1c71d8c376b6afaac54f468914',
  ),
  'pages/logout.php' => 
  array (
    'size' => 91,
    'md5' => 'fb234c1c641adadb4abf9fb61cf0a419',
  ),
  'pages/notifications.php' => 
  array (
    'size' => 1336,
    'md5' => 'acbb40ea2e78b4e1f28a0412b8c03792',
  ),
  'pages/profile.php' => 
  array (
    'size' => 3569,
    'md5' => 'e4afcabc080943b276cfd3c4af92ac4b',
  ),
  'pages/ticket_new.php' => 
  array (
    'size' => 3759,
    'md5' => 'f62a2cea6eaf6b8ec8c9147ea55f565b',
  ),
  'pages/ticket_view.php' => 
  array (
    'size' => 11460,
    'md5' => '62a17373bc25dea259c87a5e1bc593d7',
  ),
  'pages/tickets.php' => 
  array (
    'size' => 4094,
    'md5' => 'f1ec76a5dbda438cef338ab76a2e29ab',
  ),
  'seed.php' => 
  array (
    'size' => 16124,
    'md5' => 'd608553650c02872ce80301d12713297',
  ),
  'sql/schema.mysql.sql' => 
  array (
    'size' => 6115,
    'md5' => '87478e74d76d3d4015e7115466a66679',
  ),
  'sql/schema.sqlite.sql' => 
  array (
    'size' => 5382,
    'md5' => 'f097f244269e7f7a5d3c26213f1f97f2',
  ),
);
