<?php
declare(strict_types=1);

/**
 * Idara — build tool: generates integrity.php (size + md5 of every shipped file).
 * Run from the project root:  php tests/make-integrity.php
 * Re-run this every time a shipped file changes.
 *
 * Included: *.php, *.css, *.js, *.sql, *.md, *.txt and the bare .htaccess.
 * Skipped:   data/, storage/, tests/, every other dotfile, integrity.php and
 *            diag.php themselves (they are not part of the released manifest).
 */

$root = dirname(__DIR__);
$skipDirs = ['data', 'storage', 'tests', '.git'];
$skipFiles = ['integrity.php', 'diag.php', '.DS_Store', '.gitignore'];
$extensions = ['php', 'css', 'js', 'sql', 'md', 'txt'];

$manifest = [];

$walk = function (string $dir, string $prefix) use (&$walk, &$manifest, $skipDirs, $skipFiles, $extensions): void {
    foreach (scandir($dir) ?: [] as $entry) {
        if ($entry === '.' || $entry === '..') {
            continue;
        }
        $path = $dir . '/' . $entry;
        $rel  = $prefix === '' ? $entry : $prefix . '/' . $entry;

        if (is_dir($path)) {
            if (in_array($entry, $skipDirs, true) || str_starts_with($entry, '.')) {
                continue;
            }
            $walk($path, $rel);
            continue;
        }
        if (in_array($entry, $skipFiles, true)) {
            continue;
        }
        // A dotfile is shipped only when it is exactly .htaccess.
        if (str_starts_with($entry, '.') && $entry !== '.htaccess') {
            continue;
        }
        $ext = strtolower(pathinfo($entry, PATHINFO_EXTENSION));
        if ($entry !== '.htaccess' && !in_array($ext, $extensions, true)) {
            continue;
        }
        $manifest[$rel] = ['size' => filesize($path), 'md5' => md5_file($path)];
    }
};

$walk($root, '');
ksort($manifest);

$code = "<?php\n// Generated by tests/make-integrity.php — do not edit by hand.\nreturn "
    . var_export($manifest, true) . ";\n";

file_put_contents($root . '/integrity.php', $code);

echo 'integrity.php written: ' . count($manifest) . " files\n";
foreach ($manifest as $rel => $meta) {
    printf("  %-45s %6d B\n", $rel, $meta['size']);
}
