<?php
declare(strict_types=1);

/**
 * Build tool — regenerates integrity.php (md5 + size of every shipped file).
 * Run from the project root:  php tests/make-integrity.php
 */

$root = dirname(__DIR__);
$skipDirs = ['data', 'storage', 'tests', '.git'];
$skipFiles = ['integrity.php', 'diag.php', '.DS_Store', '.gitignore'];
$extensions = ['php', 'css', 'js', 'sql', 'md', 'txt'];

$manifest = [];
$walk = function (string $dir, string $prefix) use (&$walk, &$manifest, $skipDirs, $skipFiles, $extensions): void {
    foreach (scandir($dir) ?: [] as $entry) {
        if ($entry === '.' || $entry === '..') {
            continue;
        }
        $path = $dir . '/' . $entry;
        $rel  = $prefix === '' ? $entry : $prefix . '/' . $entry;
        if (is_dir($path)) {
            if (in_array($entry, $skipDirs, true) || str_starts_with($entry, '.')) {
                continue;
            }
            $walk($path, $rel);
            continue;
        }
        if (in_array($entry, $skipFiles, true)) {
            continue;
        }
        $ext = strtolower(pathinfo($entry, PATHINFO_EXTENSION));
        if (!str_starts_with($entry, '.') && !in_array($ext, $extensions, true)) {
            continue;
        }
        $manifest[$rel] = ['size' => filesize($path), 'md5' => md5_file($path)];
    }
};
$walk($root, '');
ksort($manifest);
file_put_contents($root . '/integrity.php', "<?php\n// Generated by tests/make-integrity.php — do not edit by hand.\nreturn " . var_export($manifest, true) . ";\n");
echo 'integrity.php written: ' . count($manifest) . " files\n";
