<?php
// Generated by tests/make-integrity.php — do not edit by hand.
return array (
  '.htaccess' => 
  array (
    'size' => 669,
    'md5' => 'db28f11175ca235cb2a30498cb39be21',
  ),
  'README.md' => 
  array (
    'size' => 8900,
    'md5' => '11ad8f23108cc94deba99cb1a63981fc',
  ),
  'UPLOAD-INSTRUCTIONS.txt' => 
  array (
    'size' => 6147,
    'md5' => '1d8fa98e89958dd1129a53b04b496d1e',
  ),
  'assets/css/style.css' => 
  array (
    'size' => 48086,
    'md5' => 'ea5087e97b038f9a9652fbd6dfe48bc4',
  ),
  'assets/js/app.js' => 
  array (
    'size' => 5908,
    'md5' => '6cd6a3867e87b51dcce7071100d50987',
  ),
  'htaccess.txt' => 
  array (
    'size' => 669,
    'md5' => 'db28f11175ca235cb2a30498cb39be21',
  ),
  'includes/auth.php' => 
  array (
    'size' => 5304,
    'md5' => '2abaa861ba19d23cff8445a0de1cde48',
  ),
  'includes/bootstrap.php' => 
  array (
    'size' => 5751,
    'md5' => '0c426ad4e6b73fac338f4403d55af151',
  ),
  'includes/customer_form.php' => 
  array (
    'size' => 2021,
    'md5' => 'b2cf9fedfe57f49c8560738fe16e03a6',
  ),
  'includes/db.php' => 
  array (
    'size' => 3408,
    'md5' => 'f7dd777b3d8d9984326b183f6c81c4b8',
  ),
  'includes/helpers.php' => 
  array (
    'size' => 10747,
    'md5' => 'f1d50ba1416e8ff9ebc8a800606fd063',
  ),
  'includes/i18n.php' => 
  array (
    'size' => 3844,
    'md5' => 'b54de19c398b539db3b7916717846983',
  ),
  'includes/job_form.php' => 
  array (
    'size' => 5288,
    'md5' => '174d85a3de1e417971b52697bb946377',
  ),
  'includes/layout.php' => 
  array (
    'size' => 13166,
    'md5' => '88ce69c39df7b6a89e74cb5270b3192a',
  ),
  'includes/models.php' => 
  array (
    'size' => 53419,
    'md5' => '448b2b7c8606cade9e7ccbd05c4730c7',
  ),
  'index.php' => 
  array (
    'size' => 2603,
    'md5' => '5df81c9199ac824f1e6a5f23b9481207',
  ),
  'install.php' => 
  array (
    'size' => 17956,
    'md5' => '0ff80b281c1ecfe711ed76513aa6fc60',
  ),
  'lang/ar.php' => 
  array (
    'size' => 33229,
    'md5' => 'bbb51bb18842f53fcbd565e040eeb3d8',
  ),
  'lang/de.php' => 
  array (
    'size' => 29779,
    'md5' => '77682c0f96f951556671fb846e0413db',
  ),
  'lang/doc-ar.php' => 
  array (
    'size' => 16039,
    'md5' => '3bfacd6f1335e1632c18d4fd04ac74ec',
  ),
  'lang/doc-de.php' => 
  array (
    'size' => 14587,
    'md5' => '8e587c1d19630aaa9da4ff1f3a4e8043',
  ),
  'lang/doc-en.php' => 
  array (
    'size' => 13283,
    'md5' => '70a14982607ed04360ac934b7f44c34b',
  ),
  'lang/en.php' => 
  array (
    'size' => 27776,
    'md5' => '4620cff8f0e2f2d3e259764ab2c6b52f',
  ),
  'pages/404.php' => 
  array (
    'size' => 595,
    'md5' => 'f48de0b1b8c3c0106f5eed2cc9514fec',
  ),
  'pages/admin/audit.php' => 
  array (
    'size' => 3171,
    'md5' => '84a43da7a2d1fc4de7cc45169d983a4d',
  ),
  'pages/admin/services.php' => 
  array (
    'size' => 8684,
    'md5' => '39e02d724bb0266ae1bb9fef069b25e8',
  ),
  'pages/admin/settings.php' => 
  array (
    'size' => 6536,
    'md5' => 'fe726ef6643c8a77a82928d6d32c4c23',
  ),
  'pages/admin/users.php' => 
  array (
    'size' => 9833,
    'md5' => '1e0bfc9ede99c6f6c3b6b37ce97e7935',
  ),
  'pages/api.php' => 
  array (
    'size' => 1509,
    'md5' => '3ba4d4fe31a67575e3848c263dcba200',
  ),
  'pages/board.php' => 
  array (
    'size' => 7249,
    'md5' => '25d100fbbc998cb88b5b600bc8a2294e',
  ),
  'pages/contract.php' => 
  array (
    'size' => 10026,
    'md5' => 'e7abbb580bffab2e47cd3e08231a6c4f',
  ),
  'pages/contracts.php' => 
  array (
    'size' => 9577,
    'md5' => '9cbee8998779b77b7a28e48d21c8d93d',
  ),
  'pages/customer.php' => 
  array (
    'size' => 9191,
    'md5' => '4a385c108ca7283215c31ed385dfd2d8',
  ),
  'pages/customer_edit.php' => 
  array (
    'size' => 1893,
    'md5' => '5f30a4727ae7f83ee69c6536086b4946',
  ),
  'pages/customer_new.php' => 
  array (
    'size' => 1712,
    'md5' => 'aa2086d62fee8ef402cb0fdb41093f69',
  ),
  'pages/customers.php' => 
  array (
    'size' => 3606,
    'md5' => '708fb870f4301cb914cd234b6353b7af',
  ),
  'pages/dashboard.php' => 
  array (
    'size' => 11823,
    'md5' => 'f9fe47b6248d84d3ad108b16f230b106',
  ),
  'pages/doc.php' => 
  array (
    'size' => 4432,
    'md5' => '71047f469569eb67a3a2298b3fbab904',
  ),
  'pages/download.php' => 
  array (
    'size' => 1289,
    'md5' => 'eafc2013183f102d3f3efc68a31c0fb2',
  ),
  'pages/invoice.php' => 
  array (
    'size' => 14844,
    'md5' => 'd9b1878b0472edfaa46bf40558a553c4',
  ),
  'pages/invoices.php' => 
  array (
    'size' => 5874,
    'md5' => 'f4036a5dfa11df1ed2d18b86533e3a34',
  ),
  'pages/job.php' => 
  array (
    'size' => 15877,
    'md5' => '24c7b79d97c5ef8d767c21589f0e3983',
  ),
  'pages/job_edit.php' => 
  array (
    'size' => 2272,
    'md5' => '2cbecfcfc2c1ac97d2885b7106eff6ac',
  ),
  'pages/job_new.php' => 
  array (
    'size' => 2477,
    'md5' => '6b2d23bbe518e44362299b14542a51ef',
  ),
  'pages/jobs.php' => 
  array (
    'size' => 5114,
    'md5' => 'a92826c865fea1ae40fd8f79e4cc0b04',
  ),
  'pages/login.php' => 
  array (
    'size' => 2895,
    'md5' => '2ddbb1e23edf33fbef752d59a27fd5a2',
  ),
  'pages/logout.php' => 
  array (
    'size' => 91,
    'md5' => 'fb234c1c641adadb4abf9fb61cf0a419',
  ),
  'pages/notifications.php' => 
  array (
    'size' => 1336,
    'md5' => 'acbb40ea2e78b4e1f28a0412b8c03792',
  ),
  'pages/parts.php' => 
  array (
    'size' => 7639,
    'md5' => '77b3f0341192c5b24063d320e8e385a0',
  ),
  'pages/profile.php' => 
  array (
    'size' => 3198,
    'md5' => 'f43776a50decd2571763b77a65693ff8',
  ),
  'pages/reports.php' => 
  array (
    'size' => 16995,
    'md5' => '67451d6105ddb04aa67b1a648177ae0f',
  ),
  'seed.php' => 
  array (
    'size' => 29452,
    'md5' => '46a565147126691e3148c476d7f02936',
  ),
  'sql/schema.mysql.sql' => 
  array (
    'size' => 10297,
    'md5' => 'c3de688079421925aecb581f7962ba0d',
  ),
  'sql/schema.sqlite.sql' => 
  array (
    'size' => 8320,
    'md5' => '186cd74ae30f187dc2281d5e0854735d',
  ),
);
