<?php
// Generated by tests/make-integrity.php — do not edit by hand.
return array (
  '.htaccess' => 
  array (
    'size' => 946,
    'md5' => '84283e0b0eb739ae5a83a1b27e7ea23d',
  ),
  'README.md' => 
  array (
    'size' => 20997,
    'md5' => 'c46e781952d817e445d23c18a8408df1',
  ),
  'UPLOAD-INSTRUCTIONS.txt' => 
  array (
    'size' => 10886,
    'md5' => 'f21496bc5a38cebbe0b4825af074b70d',
  ),
  'assets/avatars/01.webp' => 
  array (
    'size' => 4860,
    'md5' => '8a3582b30e9b07f7eb8020e467122e82',
  ),
  'assets/avatars/02.webp' => 
  array (
    'size' => 4558,
    'md5' => 'd8476b7b9ee785b9364bcc334dd6810e',
  ),
  'assets/avatars/03.webp' => 
  array (
    'size' => 6944,
    'md5' => 'b32cb815f2078d237a620b6095e0783a',
  ),
  'assets/avatars/04.webp' => 
  array (
    'size' => 5342,
    'md5' => '26d34c08ddc9928a45c71fef9fb31f09',
  ),
  'assets/avatars/05.webp' => 
  array (
    'size' => 6798,
    'md5' => 'c1cf3a7781187694de40a2577f11cdec',
  ),
  'assets/avatars/06.webp' => 
  array (
    'size' => 9674,
    'md5' => '4368980cd09490ce2b95934ffa4f709b',
  ),
  'assets/avatars/07.webp' => 
  array (
    'size' => 4324,
    'md5' => 'c40e1668d69bbc50eb29856107e56758',
  ),
  'assets/avatars/08.webp' => 
  array (
    'size' => 4926,
    'md5' => 'c56eaa5e34fc5c80bfae000f71edd812',
  ),
  'assets/avatars/09.webp' => 
  array (
    'size' => 6546,
    'md5' => '96ab911b3e18c06e74c90116894646aa',
  ),
  'assets/avatars/10.webp' => 
  array (
    'size' => 5460,
    'md5' => '860e52004c6cda4cd42b5728ac539973',
  ),
  'assets/avatars/11.webp' => 
  array (
    'size' => 5142,
    'md5' => 'c419a123212e13205ccbc04a78a8353b',
  ),
  'assets/avatars/12.webp' => 
  array (
    'size' => 5360,
    'md5' => '5f454c0921b029e5d5a1583ff7e4353e',
  ),
  'assets/avatars/13.webp' => 
  array (
    'size' => 7454,
    'md5' => '67b0880afb890931cfc5484998a7c1cc',
  ),
  'assets/avatars/14.webp' => 
  array (
    'size' => 5518,
    'md5' => '395d1ceb4b55a0005178b4db9fe2e4e3',
  ),
  'assets/avatars/15.webp' => 
  array (
    'size' => 4884,
    'md5' => 'd50705cc86cdef86d7703110fb8e91ba',
  ),
  'assets/avatars/16.webp' => 
  array (
    'size' => 4148,
    'md5' => '7a9e37183387f072d35e0c292812516b',
  ),
  'assets/avatars/17.webp' => 
  array (
    'size' => 4622,
    'md5' => 'e51340268ba437481ae861d71161091c',
  ),
  'assets/avatars/18.webp' => 
  array (
    'size' => 6094,
    'md5' => 'e6c3b8be6c3139cbf2edc64be86fc70f',
  ),
  'assets/avatars/19.webp' => 
  array (
    'size' => 6596,
    'md5' => '50ea4c87a8a21e9118cc3ba60202b72d',
  ),
  'assets/avatars/20.webp' => 
  array (
    'size' => 5772,
    'md5' => '01d67ee86ad6fc203090f0285dcb3bef',
  ),
  'assets/avatars/21.webp' => 
  array (
    'size' => 6894,
    'md5' => '856174a68fa8579acae59c9fb8835ebe',
  ),
  'assets/avatars/22.webp' => 
  array (
    'size' => 5304,
    'md5' => '7410542267da642c24717995e1229e5d',
  ),
  'assets/avatars/23.webp' => 
  array (
    'size' => 5506,
    'md5' => '75509817e06d0def8edf19b157462acc',
  ),
  'assets/avatars/24.webp' => 
  array (
    'size' => 5436,
    'md5' => '2b81121c6d286d259282aff3aadd7b04',
  ),
  'assets/avatars/25.webp' => 
  array (
    'size' => 4438,
    'md5' => '00f80b7c756e4e92f686ce48e59c4af0',
  ),
  'assets/avatars/26.webp' => 
  array (
    'size' => 4316,
    'md5' => '4ab8394d3cc7609caf4ba00327746abe',
  ),
  'assets/avatars/27.webp' => 
  array (
    'size' => 3924,
    'md5' => '688fae06f458554a649e0dd74fe78546',
  ),
  'assets/avatars/28.webp' => 
  array (
    'size' => 4282,
    'md5' => '46ef4e486dc2791d05d1ae74a62bf681',
  ),
  'assets/avatars/29.webp' => 
  array (
    'size' => 3756,
    'md5' => '0a8a9c1c42f4c0c12c6c8ed7ff987760',
  ),
  'assets/avatars/30.webp' => 
  array (
    'size' => 5224,
    'md5' => '04b705c3e35daace0ef02f1567f8983b',
  ),
  'assets/avatars/31.webp' => 
  array (
    'size' => 4304,
    'md5' => '671233500e990687971613f2cdd00127',
  ),
  'assets/avatars/32.webp' => 
  array (
    'size' => 5890,
    'md5' => 'f650a9ef32ba6971b46f6ae7d23cde94',
  ),
  'assets/css/style.css' => 
  array (
    'size' => 50078,
    'md5' => '71ee4b1ea9e298d4a24142285b8e5414',
  ),
  'assets/js/app.js' => 
  array (
    'size' => 5808,
    'md5' => 'f8cb7079e7eec9c2067c0509f525d82c',
  ),
  'htaccess.txt' => 
  array (
    'size' => 946,
    'md5' => '84283e0b0eb739ae5a83a1b27e7ea23d',
  ),
  'includes/auth.php' => 
  array (
    'size' => 5134,
    'md5' => '9d9791c33fb395cb2e7de51ed7ff9c9f',
  ),
  'includes/bootstrap.php' => 
  array (
    'size' => 3950,
    'md5' => 'fcb00024c18bb4628168b7b4bde876d4',
  ),
  'includes/db.php' => 
  array (
    'size' => 4275,
    'md5' => '579f8a3b8132c9ad33a75c6abfa90804',
  ),
  'includes/helpers.php' => 
  array (
    'size' => 13347,
    'md5' => 'fea14fc81b7c664e19675ca51f9e9293',
  ),
  'includes/i18n.php' => 
  array (
    'size' => 3869,
    'md5' => '14ed7f56db15efd0d883080e11275a8c',
  ),
  'includes/layout.php' => 
  array (
    'size' => 18143,
    'md5' => '1fc13f263a200f1f1f33bb76cc784860',
  ),
  'includes/models.php' => 
  array (
    'size' => 71724,
    'md5' => 'ab33be851c5e061290bf5d34f4b07159',
  ),
  'index.php' => 
  array (
    'size' => 2854,
    'md5' => '85763cf93abb68487866c255092d88ae',
  ),
  'install.php' => 
  array (
    'size' => 18600,
    'md5' => '0a470b1c44bb6d3b0344ec6f5bb4b837',
  ),
  'lang/ar.php' => 
  array (
    'size' => 38117,
    'md5' => '69565b8525b12f2a7e07c69ba131d92a',
  ),
  'lang/doc-ar.php' => 
  array (
    'size' => 18287,
    'md5' => '863d1f5311dc0acfaa4079ed9175c6d6',
  ),
  'lang/doc-en.php' => 
  array (
    'size' => 15006,
    'md5' => 'f7c1ed3a60c7b4b7f6c362d0de50aa3c',
  ),
  'lang/en.php' => 
  array (
    'size' => 31646,
    'md5' => '7c2e7dbe8f941f5a162edd1c02024847',
  ),
  'pages/404.php' => 
  array (
    'size' => 907,
    'md5' => 'e55749c86449ef048f75b35feb20df9a',
  ),
  'pages/admin/audit.php' => 
  array (
    'size' => 3257,
    'md5' => '410d4f88064e7b5cb8ba389acbae908a',
  ),
  'pages/admin/categories.php' => 
  array (
    'size' => 4563,
    'md5' => '0880cfe43945f38ff1294535d6480f49',
  ),
  'pages/admin/departments.php' => 
  array (
    'size' => 6640,
    'md5' => '9a3bf2c9da3114b02859be6fb6f9ca9d',
  ),
  'pages/admin/reports.php' => 
  array (
    'size' => 10139,
    'md5' => 'fc0f8f10a40158916bde18a714304a0c',
  ),
  'pages/admin/settings.php' => 
  array (
    'size' => 3038,
    'md5' => '56a158a5cd4dae78be9951cda61df558',
  ),
  'pages/admin/types.php' => 
  array (
    'size' => 4537,
    'md5' => '7c4a41020b29429c7f141749c697a6cb',
  ),
  'pages/admin/users.php' => 
  array (
    'size' => 10821,
    'md5' => '81aba8b8208294b4eae7fbab64e0dc8b',
  ),
  'pages/api.php' => 
  array (
    'size' => 1919,
    'md5' => 'bb2967bdb344779d409729829ee132f8',
  ),
  'pages/approval_new.php' => 
  array (
    'size' => 8003,
    'md5' => '4376f6b173755d8f0933a2f4c559f7a4',
  ),
  'pages/approval_view.php' => 
  array (
    'size' => 14941,
    'md5' => '2df591332f772816f1bf57fab11ba544',
  ),
  'pages/approvals.php' => 
  array (
    'size' => 4640,
    'md5' => '4c20910b6ba747a49d04c80f311b6df6',
  ),
  'pages/calendar.php' => 
  array (
    'size' => 6334,
    'md5' => 'e30e815ccb2d342c8cdd9c9ab74eaa88',
  ),
  'pages/correspondence.php' => 
  array (
    'size' => 5673,
    'md5' => '21beb7b0ac04814a5bea9d2bf137a425',
  ),
  'pages/dashboard.php' => 
  array (
    'size' => 8853,
    'md5' => '02062df5d75e61102c815083dc839299',
  ),
  'pages/delegations.php' => 
  array (
    'size' => 8252,
    'md5' => 'dd478bb54855a21915f674bc2f7eb0ef',
  ),
  'pages/doc.php' => 
  array (
    'size' => 5332,
    'md5' => 'c997be42f7c0ee0e973c0e7faf5bdaad',
  ),
  'pages/download.php' => 
  array (
    'size' => 3311,
    'md5' => 'e9fd2d4c78b5efc797b228a963292255',
  ),
  'pages/letter_new.php' => 
  array (
    'size' => 5953,
    'md5' => '1ebab2e9dc62d8dd2f7a441f0a8d97bc',
  ),
  'pages/letter_view.php' => 
  array (
    'size' => 9282,
    'md5' => 'afaa59a009133d25db5a91257f7a8708',
  ),
  'pages/login.php' => 
  array (
    'size' => 2895,
    'md5' => '4f1945c492a4c67cfbebea6a67a21f39',
  ),
  'pages/logout.php' => 
  array (
    'size' => 102,
    'md5' => '204d74e5f0a7e9a36815efff16bc02c8',
  ),
  'pages/meeting_view.php' => 
  array (
    'size' => 12506,
    'md5' => 'a1a1bcca70e8f8b182ec521b2821d988',
  ),
  'pages/meetings.php' => 
  array (
    'size' => 6669,
    'md5' => 'd0bb46d1a1cdfd9655df5197d07a8d6c',
  ),
  'pages/notifications.php' => 
  array (
    'size' => 1502,
    'md5' => 'f37f5a73a1bb9e584c76cec52e15e667',
  ),
  'pages/profile.php' => 
  array (
    'size' => 8843,
    'md5' => 'c0ec280ab4a7ef25c2649443c7954df7',
  ),
  'pages/task_new.php' => 
  array (
    'size' => 6625,
    'md5' => '29f7367b6accd391afce15b262a7892d',
  ),
  'pages/task_view.php' => 
  array (
    'size' => 19241,
    'md5' => '89eff4bfabdf07e961a1df047bf00db5',
  ),
  'pages/tasks.php' => 
  array (
    'size' => 6032,
    'md5' => 'c8bb3513510d6a52cb91e893a14079d4',
  ),
  'pages/team.php' => 
  array (
    'size' => 4327,
    'md5' => '6607f4e66f908db64bd3c26419abe50a',
  ),
  'seed.php' => 
  array (
    'size' => 27000,
    'md5' => '4f71d69e5bdcfa60ce86604e88a68a39',
  ),
  'sql/schema.mysql.sql' => 
  array (
    'size' => 9105,
    'md5' => '57cd6ac22ba26468fc6c33a9390ab3da',
  ),
  'sql/schema.sqlite.sql' => 
  array (
    'size' => 7791,
    'md5' => '62bbefc3a9f403c9413b22ead27b9c78',
  ),
);
