<?php
// Generated by tests/make-integrity.php — do not edit by hand.
return array (
  '.htaccess' => 
  array (
    'size' => 946,
    'md5' => '84283e0b0eb739ae5a83a1b27e7ea23d',
  ),
  'README.md' => 
  array (
    'size' => 20997,
    'md5' => 'c46e781952d817e445d23c18a8408df1',
  ),
  'UPLOAD-INSTRUCTIONS.txt' => 
  array (
    'size' => 9250,
    'md5' => 'f14670a96f391c910390482d7e820348',
  ),
  'assets/css/style.css' => 
  array (
    'size' => 45573,
    'md5' => '40e79a9f15755a55cfb9ab4f65140bd3',
  ),
  'assets/js/app.js' => 
  array (
    'size' => 4429,
    'md5' => '330be7084740458d8760553743dd8931',
  ),
  'htaccess.txt' => 
  array (
    'size' => 946,
    'md5' => '84283e0b0eb739ae5a83a1b27e7ea23d',
  ),
  'includes/auth.php' => 
  array (
    'size' => 5134,
    'md5' => '9d9791c33fb395cb2e7de51ed7ff9c9f',
  ),
  'includes/bootstrap.php' => 
  array (
    'size' => 3950,
    'md5' => 'fcb00024c18bb4628168b7b4bde876d4',
  ),
  'includes/db.php' => 
  array (
    'size' => 4275,
    'md5' => '579f8a3b8132c9ad33a75c6abfa90804',
  ),
  'includes/helpers.php' => 
  array (
    'size' => 12362,
    'md5' => '0b594683e752500d2a6437fd2dfb7ab1',
  ),
  'includes/i18n.php' => 
  array (
    'size' => 3869,
    'md5' => '14ed7f56db15efd0d883080e11275a8c',
  ),
  'includes/layout.php' => 
  array (
    'size' => 16927,
    'md5' => 'f0bf2e3709637c640af77024777daf36',
  ),
  'includes/models.php' => 
  array (
    'size' => 64823,
    'md5' => 'fd80b6dd18fac85ccd6614bf6609ebb2',
  ),
  'index.php' => 
  array (
    'size' => 2854,
    'md5' => '85763cf93abb68487866c255092d88ae',
  ),
  'install.php' => 
  array (
    'size' => 18600,
    'md5' => '0a470b1c44bb6d3b0344ec6f5bb4b837',
  ),
  'lang/ar.php' => 
  array (
    'size' => 35252,
    'md5' => 'ff7f7ad4f61e02e8c4efff48d99e4c44',
  ),
  'lang/doc-ar.php' => 
  array (
    'size' => 18287,
    'md5' => '863d1f5311dc0acfaa4079ed9175c6d6',
  ),
  'lang/doc-en.php' => 
  array (
    'size' => 15006,
    'md5' => 'f7c1ed3a60c7b4b7f6c362d0de50aa3c',
  ),
  'lang/en.php' => 
  array (
    'size' => 29277,
    'md5' => 'fd44b9769539a5d41c877cdd24bab79b',
  ),
  'pages/404.php' => 
  array (
    'size' => 907,
    'md5' => 'e55749c86449ef048f75b35feb20df9a',
  ),
  'pages/admin/audit.php' => 
  array (
    'size' => 2606,
    'md5' => '02d575a29900c249e426b57737815acb',
  ),
  'pages/admin/categories.php' => 
  array (
    'size' => 4375,
    'md5' => '247cf67132018b18fa6897136877e7f7',
  ),
  'pages/admin/departments.php' => 
  array (
    'size' => 6455,
    'md5' => 'a5945b212e46567ee3fb5341f2bf7e11',
  ),
  'pages/admin/reports.php' => 
  array (
    'size' => 10139,
    'md5' => 'fc0f8f10a40158916bde18a714304a0c',
  ),
  'pages/admin/settings.php' => 
  array (
    'size' => 3038,
    'md5' => '56a158a5cd4dae78be9951cda61df558',
  ),
  'pages/admin/types.php' => 
  array (
    'size' => 4350,
    'md5' => '11a6b72d7c4122e612e8ab6245db1f9f',
  ),
  'pages/admin/users.php' => 
  array (
    'size' => 9525,
    'md5' => 'fae64922774967b28e1a55c20105db8b',
  ),
  'pages/api.php' => 
  array (
    'size' => 1919,
    'md5' => 'bb2967bdb344779d409729829ee132f8',
  ),
  'pages/approval_new.php' => 
  array (
    'size' => 7485,
    'md5' => '767db010171faebf272b9b7f3a9d447a',
  ),
  'pages/approval_view.php' => 
  array (
    'size' => 13704,
    'md5' => 'fb39cc2fd65371d52c17396146b508ad',
  ),
  'pages/approvals.php' => 
  array (
    'size' => 4640,
    'md5' => '4c20910b6ba747a49d04c80f311b6df6',
  ),
  'pages/calendar.php' => 
  array (
    'size' => 5510,
    'md5' => '96e3d7cfd45a9cb52353b129ba236115',
  ),
  'pages/correspondence.php' => 
  array (
    'size' => 5673,
    'md5' => '21beb7b0ac04814a5bea9d2bf137a425',
  ),
  'pages/dashboard.php' => 
  array (
    'size' => 8615,
    'md5' => 'e49aee897b8083f90e61e76dbb06cc6f',
  ),
  'pages/delegations.php' => 
  array (
    'size' => 8682,
    'md5' => 'dfcdc10c0bbcf54faa8ffa76cbb3f17c',
  ),
  'pages/doc.php' => 
  array (
    'size' => 5332,
    'md5' => 'c997be42f7c0ee0e973c0e7faf5bdaad',
  ),
  'pages/download.php' => 
  array (
    'size' => 2424,
    'md5' => 'ce3b05226ef3f2a76b14e4dfe42aed58',
  ),
  'pages/letter_new.php' => 
  array (
    'size' => 5953,
    'md5' => '1ebab2e9dc62d8dd2f7a441f0a8d97bc',
  ),
  'pages/letter_view.php' => 
  array (
    'size' => 8820,
    'md5' => '70587c6678eb67b3be67543204d07fa3',
  ),
  'pages/login.php' => 
  array (
    'size' => 2895,
    'md5' => '4f1945c492a4c67cfbebea6a67a21f39',
  ),
  'pages/logout.php' => 
  array (
    'size' => 102,
    'md5' => '204d74e5f0a7e9a36815efff16bc02c8',
  ),
  'pages/meeting_view.php' => 
  array (
    'size' => 12066,
    'md5' => '3632402d36e5c14247026355f3c6d2c7',
  ),
  'pages/meetings.php' => 
  array (
    'size' => 6598,
    'md5' => '22c6eae68d7b2d7d913c923913462bdd',
  ),
  'pages/notifications.php' => 
  array (
    'size' => 1502,
    'md5' => 'f37f5a73a1bb9e584c76cec52e15e667',
  ),
  'pages/profile.php' => 
  array (
    'size' => 4123,
    'md5' => '16da047f48d04e58175664f0e17b3d41',
  ),
  'pages/task_new.php' => 
  array (
    'size' => 6625,
    'md5' => '29f7367b6accd391afce15b262a7892d',
  ),
  'pages/task_view.php' => 
  array (
    'size' => 17922,
    'md5' => '36679a7f922d385d4ac5f434c384e999',
  ),
  'pages/tasks.php' => 
  array (
    'size' => 5415,
    'md5' => 'e9054c2f57d616e969af840e15a0aac8',
  ),
  'pages/team.php' => 
  array (
    'size' => 4368,
    'md5' => '2f1e288dedd350d51c75391fe1f2458e',
  ),
  'seed.php' => 
  array (
    'size' => 26603,
    'md5' => '3ac23ea7f5003bb4c49ee31a9c3779cd',
  ),
  'sql/schema.mysql.sql' => 
  array (
    'size' => 8977,
    'md5' => '53cfb4b3eb82df56e1252c72710dae82',
  ),
  'sql/schema.sqlite.sql' => 
  array (
    'size' => 7685,
    'md5' => '833f53957d22eb79c88755620f490ba9',
  ),
);
