<?php
// Generated by tests/make-integrity.php — do not edit by hand.
return array (
  '.htaccess' => 
  array (
    'size' => 662,
    'md5' => '1ccfe15beae593b2a37e0f20e6c89882',
  ),
  'README.md' => 
  array (
    'size' => 20997,
    'md5' => 'c46e781952d817e445d23c18a8408df1',
  ),
  'UPLOAD-INSTRUCTIONS.txt' => 
  array (
    'size' => 8098,
    'md5' => 'ee0af2b0db8121dd1ab64d3cfffedcc3',
  ),
  'assets/css/style.css' => 
  array (
    'size' => 45128,
    'md5' => 'f1b4f84e6e9b99e0a48cd51e0ab864d1',
  ),
  'assets/js/app.js' => 
  array (
    'size' => 4429,
    'md5' => '330be7084740458d8760553743dd8931',
  ),
  'htaccess.txt' => 
  array (
    'size' => 662,
    'md5' => '1ccfe15beae593b2a37e0f20e6c89882',
  ),
  'includes/auth.php' => 
  array (
    'size' => 4647,
    'md5' => 'acecabc29e8fd674f7cd561707bfcf7b',
  ),
  'includes/bootstrap.php' => 
  array (
    'size' => 3950,
    'md5' => 'fcb00024c18bb4628168b7b4bde876d4',
  ),
  'includes/db.php' => 
  array (
    'size' => 2855,
    'md5' => '787ee9ee57b932c787152cd9ca57e240',
  ),
  'includes/helpers.php' => 
  array (
    'size' => 12311,
    'md5' => 'befae0bd244e8f6443bc1b23850dd556',
  ),
  'includes/i18n.php' => 
  array (
    'size' => 3869,
    'md5' => '14ed7f56db15efd0d883080e11275a8c',
  ),
  'includes/layout.php' => 
  array (
    'size' => 16739,
    'md5' => '5d997778a10e74f935ebf576e67331c6',
  ),
  'includes/models.php' => 
  array (
    'size' => 59120,
    'md5' => 'bfd17c6d31b7177be1f02fc73ff6eeec',
  ),
  'index.php' => 
  array (
    'size' => 2584,
    'md5' => 'e8cb7e71cafea6f08247d89a01bfc446',
  ),
  'install.php' => 
  array (
    'size' => 18446,
    'md5' => 'b6cb1e4a82f027c07f6893db21fef82b',
  ),
  'lang/ar.php' => 
  array (
    'size' => 33554,
    'md5' => 'daadfc89303654da289833933f3d15c6',
  ),
  'lang/doc-ar.php' => 
  array (
    'size' => 18287,
    'md5' => '863d1f5311dc0acfaa4079ed9175c6d6',
  ),
  'lang/doc-en.php' => 
  array (
    'size' => 15006,
    'md5' => 'f7c1ed3a60c7b4b7f6c362d0de50aa3c',
  ),
  'lang/en.php' => 
  array (
    'size' => 27926,
    'md5' => '39cf7f2ab9281d9f9bfc8e61ddfea179',
  ),
  'pages/404.php' => 
  array (
    'size' => 907,
    'md5' => 'e55749c86449ef048f75b35feb20df9a',
  ),
  'pages/admin/audit.php' => 
  array (
    'size' => 2606,
    'md5' => '02d575a29900c249e426b57737815acb',
  ),
  'pages/admin/categories.php' => 
  array (
    'size' => 4375,
    'md5' => '2262b35aa85993346a74d7c26077d9f3',
  ),
  'pages/admin/departments.php' => 
  array (
    'size' => 6455,
    'md5' => 'a5945b212e46567ee3fb5341f2bf7e11',
  ),
  'pages/admin/reports.php' => 
  array (
    'size' => 10097,
    'md5' => '4e2a08a6549396419795292737338d7b',
  ),
  'pages/admin/settings.php' => 
  array (
    'size' => 3038,
    'md5' => '56a158a5cd4dae78be9951cda61df558',
  ),
  'pages/admin/types.php' => 
  array (
    'size' => 4350,
    'md5' => '0b8280308766d635e11dd632a6f938f6',
  ),
  'pages/admin/users.php' => 
  array (
    'size' => 9651,
    'md5' => '79bab408cc5c84e1e9ccc46e11a5690a',
  ),
  'pages/api.php' => 
  array (
    'size' => 1919,
    'md5' => 'bb2967bdb344779d409729829ee132f8',
  ),
  'pages/approval_new.php' => 
  array (
    'size' => 7485,
    'md5' => '767db010171faebf272b9b7f3a9d447a',
  ),
  'pages/approval_view.php' => 
  array (
    'size' => 8018,
    'md5' => 'b84b91a6596892cd0c7311a176315130',
  ),
  'pages/approvals.php' => 
  array (
    'size' => 4640,
    'md5' => '4c20910b6ba747a49d04c80f311b6df6',
  ),
  'pages/calendar.php' => 
  array (
    'size' => 5510,
    'md5' => '96e3d7cfd45a9cb52353b129ba236115',
  ),
  'pages/correspondence.php' => 
  array (
    'size' => 5673,
    'md5' => '21beb7b0ac04814a5bea9d2bf137a425',
  ),
  'pages/dashboard.php' => 
  array (
    'size' => 8510,
    'md5' => '0de342ce3ca5d22e39830b3bc8c511f9',
  ),
  'pages/delegations.php' => 
  array (
    'size' => 8488,
    'md5' => '77c6e2a24b570be17125f0c83c83db26',
  ),
  'pages/doc.php' => 
  array (
    'size' => 5332,
    'md5' => 'c997be42f7c0ee0e973c0e7faf5bdaad',
  ),
  'pages/download.php' => 
  array (
    'size' => 2424,
    'md5' => 'ce3b05226ef3f2a76b14e4dfe42aed58',
  ),
  'pages/letter_new.php' => 
  array (
    'size' => 5953,
    'md5' => '1ebab2e9dc62d8dd2f7a441f0a8d97bc',
  ),
  'pages/letter_view.php' => 
  array (
    'size' => 8820,
    'md5' => '70587c6678eb67b3be67543204d07fa3',
  ),
  'pages/login.php' => 
  array (
    'size' => 2895,
    'md5' => '4f1945c492a4c67cfbebea6a67a21f39',
  ),
  'pages/logout.php' => 
  array (
    'size' => 102,
    'md5' => '204d74e5f0a7e9a36815efff16bc02c8',
  ),
  'pages/meeting_view.php' => 
  array (
    'size' => 8896,
    'md5' => '4fbb388f741a57c69888ce3a343ab1fc',
  ),
  'pages/meetings.php' => 
  array (
    'size' => 6461,
    'md5' => '4a7fb543d6aec2e0013149ae7bbd67cb',
  ),
  'pages/notifications.php' => 
  array (
    'size' => 1502,
    'md5' => 'f37f5a73a1bb9e584c76cec52e15e667',
  ),
  'pages/profile.php' => 
  array (
    'size' => 4090,
    'md5' => '8154caebb14ea7fbbb77da18188c31ef',
  ),
  'pages/task_new.php' => 
  array (
    'size' => 6625,
    'md5' => '29f7367b6accd391afce15b262a7892d',
  ),
  'pages/task_view.php' => 
  array (
    'size' => 17922,
    'md5' => '36679a7f922d385d4ac5f434c384e999',
  ),
  'pages/tasks.php' => 
  array (
    'size' => 5415,
    'md5' => 'e9054c2f57d616e969af840e15a0aac8',
  ),
  'pages/team.php' => 
  array (
    'size' => 4368,
    'md5' => '2f1e288dedd350d51c75391fe1f2458e',
  ),
  'seed.php' => 
  array (
    'size' => 26603,
    'md5' => '3ac23ea7f5003bb4c49ee31a9c3779cd',
  ),
  'sql/schema.mysql.sql' => 
  array (
    'size' => 8923,
    'md5' => '6c89b7bfbb3af31540242cc6762392ec',
  ),
  'sql/schema.sqlite.sql' => 
  array (
    'size' => 7634,
    'md5' => '164afc9d815c552c3825e0fb713ab6f3',
  ),
);
